version: "3"

services:
  cast-builder:
    container_name: cast-builder
    build:
      context: ./
      dockerfile: builder/Dockerfile
    volumes:
      - ./builder:/source
      - ./shared:/shared
  
  reranker:
    container_name: reranker
    build:
      context: ./
      dockerfile: reranker/Dockerfile
    volumes:
    - ./reranker:/source
    - ./shared:/shared
    depends_on:
      - cast-builder
      - searcher
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
  
  # rewriter:
  #   container_name: rewriter
  #   build:
  #     context: ./
  #     dockerfile: rewriter/Dockerfile
  #   volumes:
  #   - ./rewriter:/source
  #   - ./shared:/shared
  #   depends_on:
  #     - cast-builder
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

  summariser:
    container_name: summariser
    build:
      context: ./
      dockerfile: summariser/Dockerfile
    volumes:
    - ./summariser:/source
    - ./shared:/shared
    depends_on:
      - cast-builder
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
  
  searcher:
    container_name: searcher
    build:
      context: ./
      dockerfile: searcher/Dockerfile
    volumes:
    - ./searcher:/source
    - ./shared:/shared
    - ../data/cast_y4_files/trecweb_index:/index
    depends_on:
      - cast-builder
  
  web_ui:
    container_name: web_ui
    build:
      context: ./
      dockerfile: web_ui/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SEARCHER_URL=searcher:8000
      - SUMMARISER_URL=summariser:8000
      - RERANKER_URL=reranker:8000
    volumes:
    - ./web_ui:/source
    - ./shared:/shared
    depends_on:
      - cast-builder
      - reranker
      - searcher
      - summariser